### ISSUE TITLE
error: "name" field doesn't match expected name "focus_detector".

### ISSUE THREAD

**Issue by vnbrew** [EdsonBueno/focus_detector#18]
I checkout my project with my new MacBook Pro, chip Apple M1

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 13.0.1 22A400 darwin-arm (Rosetta), locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.75.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

```
dependencies:
  focus_detector:
    git:
      url: https://github.com/ifnyas/focus_detector.git
      ref: master
```
 
And got an error after run: flutter pub get

Error on line 1, column 7: "name" field doesn't match expected name "focus_detector".
  ╷
1 │ name: focus_detector_v2
  │       ^^^^^^^^^^^^^^^^^
  ╵
pub get failed (65;   ╵)
exit code 65
